name: Pylint(lint all, badge once)

on:
  push:
    branches: [ main, master ]          # update badge only on real pushes
  pull_request:
    branches: [ main, master ]          # PRs lint but do NOT push a badge
  workflow_dispatch:                    # manual run button

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:                        # needed so the 3.12 job can commit
      contents: write

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install project deps + pylint
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pylint

      # ----------  Plain lint for ALL matrix entries ----------
      - name: Run Pylint (quality gate)
        run: |
          pylint --fail-under=8 $(git ls-files '*.py')

      # ----------  Badge update ONLY on Python 3.12 ----------
      - name: Update README badge (only 3.12 push)
        if: |
          matrix.python-version == '3.12' && github.event_name == 'push'
        uses: Silleellie/pylint-github-action@v2.1
        with:
          python-version: ${{ matrix.python-version }}     # must match runner
          lint-path: |
            animals
            data
            gui
            main.py
          pylintrc-path: .pylintrc
          requirements-path: requirements.txt
          readme-path: README.md
          badge-text: PyLint
